# Generated by Django 3.2.5 on 2021-07-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbalance',
            name='client',
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
